name: Test
on:
  push:
    branches: [ main, expert-two ]
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
       xcodebuild clean build -workspace "Gimmiek.xcworkspace" -scheme "Gimmiek" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
     
    - name: Test
      run: |
           xcodebuild clean test -workspace "GimmiekTests.xcworkspace" -scheme "GimmiekTests" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
